### ISSUE TITLE
Polygon filters duplicate after editing

### ISSUE THREAD

**Issue by paulmueller** [DC-analysis/DCscope#148]
When editing polygon filters, sometimes they become duplicates (new filter is created instead of a filter being edited).

**Comment by paulmueller** [comment]
Here another occurence of the issue. Could this be a race condition?

![image](https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut2/assets/2853022/0c98e899-56ab-478b-976f-a534c1a50acb)

**Comment by paulmueller** [comment]
The above commit (https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut2/commit/650188b42484d45772aff6c21c2719611549e3c5#r151502087) could be a potential fix for this issue. Since it is hard to reproduce, I will keep it open and label it as "possibly-fixed".

Please report here if this issue occurs in versions 2.21.2 or higher.

**Comment by paulmueller** [comment]
Report from a user 

- Ich arbeite an einem Datensatz mit dem Filter set A, das den Polygon Filter B aktiviert hat
- Bei Polygon Filter gehe ich auf Choose --> Polygon Filter B, sodass der Filter über dem QV Plot eingeblendet wird
- jetzt wähle ich im Filter set A den Polygon Filter B ab und klicke Apply
- Sobald ich jetzt beim Polygon Filter auf Save drücke (egal ob der Filter verändert wurde oder nicht), wird der Filter verdoppelt

Den Filter kann ich dann auch nicht mehr löschen:

![Image](https://github.com/user-attachments/assets/30812383-9e0d-42dd-8fee-d83ab29ff3f9)

**Comment by paulmueller** [comment]
I can reproduce. Attempting to delete the second filter results in this error for me.

```python
Unhandled exception in Shape-Out version 2.21.5.post4+g7ff78ec:
Traceback (most recent call last):
  File "/home/paul/repos-work/DC/ShapeOut2/shapeout2/gui/widgets/wait_cursor.py", line 31, in wrapper
    ret = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/paul/repos-work/DC/ShapeOut2/shapeout2/gui/main.py", line 997, in on_quickview_refresh
    self.on_quickview_show_dataset(slot_index, filt_index,
  File "/home/paul/repos-work/DC/ShapeOut2/shapeout2/gui/widgets/wait_cursor.py", line 31, in wrapper
    ret = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/paul/repos-work/DC/ShapeOut2/shapeout2/gui/main.py", line 1022, in on_quickview_show_dataset
    ds = self.pipeline.get_dataset(slot_index=slot_index,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paul/repos-work/DC/ShapeOut2/shapeout2/pipeline/core.py", line 309, in get_dataset
    ds = ray.get_dataset(filters, apply_filter=apply_filter)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paul/repos-work/DC/ShapeOut2/shapeout2/pipeline/filter_ray.py", line 164, in get_dataset
    ds = self.get_final_child(apply_filter=apply_filter)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paul/repos-work/DC/ShapeOut2/shapeout2/pipeline/filter_ray.py", line 141, in get_final_child
    final_ds.apply_filter()
  File "/home/paul/repos-work/DC/dclab/dclab/rtdc_dataset/fmt_hierarchy/base.py", line 257, in apply_filter
    super(RTDC_Hierarchy, self).apply_filter(*args, **kwargs)
  File "/home/paul/repos-work/DC/dclab/dclab/rtdc_dataset/core.py", line 521, in apply_filter
    self.filter.update(rtdc_ds=self, force=force)
  File "/home/paul/repos-work/DC/dclab/dclab/rtdc_dataset/filter.py", line 133, in update
    self._init_rtdc_ds(rtdc_ds)
  File "/home/paul/repos-work/DC/dclab/dclab/rtdc_dataset/filter.py", line 93, in _init_rtdc_ds
    pf = PolygonFilter.get_instance_from_id(pf_id)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paul/repos-work/DC/dclab/dclab/polygon_filter.py", line 264, in get_instance_from_id
    raise KeyError("PolygonFilter with unique_id {} not found.".
KeyError: 'PolygonFilter with unique_id 4 not found.'
```
