### ISSUE TITLE
Export of internal basin data fails

### ISSUE THREAD

**Issue by paulmueller** [DC-analysis/DCscope#164]
When a dataset has internal basin data defined, exporting to .rtdc with basins fails:

```python
Unhandled exception in Shape-Out version 2.16.2:
Traceback (most recent call last):
  File "/home/paul/repos/ShapeOut2/shapeout2/gui/export/e2data.py", line 86, in done
    self.export_data()
  File "/home/paul/repos/ShapeOut2/shapeout2/gui/widgets/wait_cursor.py", line 31, in wrapper
    ret = func(*args, **kwargs)
  File "/home/paul/repos/ShapeOut2/shapeout2/gui/export/e2data.py", line 127, in export_data
    ds.export.hdf5(
  File "/home/paul/repos/dclab/dclab/rtdc_dataset/export.py", line 444, in hdf5
    hw.store_basin(**bn_dict, verify=False)
  File "/home/paul/repos/dclab/dclab/rtdc_dataset/writer.py", line 247, in store_basin
    raise ValueError(
ValueError: When writing an internal basin, you must specify `internal_data` which is either a dictionary of numpy arrays or an `h5py.Group` containing the relevant datasets.
```

**Comment by paulmueller** [comment]
See https://github.com/DC-analysis/dclab/issues/262
