### ISSUE TITLE
Sometimes plots are incorrect (number of plots, datasets plotted).

### ISSUE THREAD

**Issue by paulmueller** [DC-analysis/DCscope#172]
![image](https://github.com/user-attachments/assets/72ff7f37-7e8b-4905-aeaf-31d0f0c17e5d)

In this exemplary screenshot, the number of datasets plotted (3) does not align with the number of datasets selected for plotting (4). There probably is something wrong with the part that plots data.

**Comment by paulmueller** [comment]
Users report that saving the session and opening again resolves the issue.

**Comment by marketakub** [comment]
This just happened to me and saving+reopening the session did not help. It happened after I tried to create a new set of plots - not only I had double the number of plots that I was supposed to have in 1 window, but also the number of filters I had suddenly doubled. Then I was not able to open the session, an error came up.:

Unhandled exception in Shape-Out version 2.17.0:
Traceback (most recent call last):
  File "ShapeOut2Launcher.py", line 4, in <module>
  File "shapeout2\__main__.py", line 35, in main
    window = ShapeOut2(*app.arguments()[1:])
  File "shapeout2\gui\main.py", line 215, in __init__
    self.on_action_open(path=apath)
  File "shapeout2\gui\main.py", line 781, in on_action_open
    session.open_session(path, self.pipeline, search_paths)
  File "shapeout2\session.py", line 353, in open_session
    import_filters(arc.open("filters.sof"), pipeline, strict=True)
  File "shapeout2\session.py", line 110, in import_filters
    import_filter_set(path, pipeline, strict)
  File "shapeout2\session.py", line 158, in import_filter_set
    filt = Filter(identifier=state["identifier"])
  File "shapeout2\pipeline\filter.py", line 42, in __init__
    raise ValueError("Filter with identifier "
ValueError: Filter with identifier 'Filter_1' already exists!

**Comment by paulmueller** [comment]
Similar to #148, I found an issue with updating the plots that could have potentially lead to this bug. See https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut2/commit/018ed1008230763bd83735efd979bee4f85aea36#r151502312

I am labeling this issue with "possibly-fixed" until there are reports with Shape-Out versions >=2.21.2.

**Comment by paulmueller** [comment]
After the refactoring I did recently, this should not happen again. If something similar happens, please create a new issue.
