### ISSUE TITLE
Quick View 'locating' error when block matrix is reduced while QV is temporarily inactive 

### ISSUE THREAD

**Issue by chrherold** [DC-analysis/DCscope#38]
The following problem occurs when switching Quick View on and off by the button in the header
in the following scenario:

- In the block matrix, there is at least 2 filtersets OR 2 datasets
- QuickView is activated and an entry is selected to be displayed
- QV is deactivated by the "Quick View" button 
- one of the alt least 2 filtersets OR datasets is removed
- QV is reactivated by the "Quick View" button

The following error is displayed:

```
Unhandled exception in Shape-Out version 2.0.0:
Traceback (most recent call last):
  File "C:\Users\Christoph\AppData\Local\Shape-Out 2\shapeout2\gui\matrix\data_matrix.py", line 564, in toggle_filter_enable
    self.publish_matrix()
  File "C:\Users\Christoph\AppData\Local\Shape-Out 2\shapeout2\gui\matrix\data_matrix.py", line 443, in publish_matrix
    self.changed_quickview()
  File "C:\Users\Christoph\AppData\Local\Shape-Out 2\shapeout2\gui\matrix\data_matrix.py", line 252, in changed_quickview
    slot_index_qv, filt_index_qv = self.get_quickview_indices()
  File "C:\Users\Christoph\AppData\Local\Shape-Out 2\shapeout2\gui\matrix\data_matrix.py", line 367, in get_quickview_indices
    slot_id, filt_id = self.get_quickview_ids()
TypeError: 'NoneType' object is not iterable
```

now if shift + click is used, in the first attempt the following error is displayed:

```
Unhandled exception in Shape-Out version 2.0.0:
Traceback (most recent call last):
  File "C:\Users\Christoph\AppData\Local\Shape-Out 2\shapeout2\gui\matrix\dm_element.py", line 52, in mousePressEvent
    self.update_content(quickview)
  File "C:\Users\Christoph\AppData\Local\Shape-Out 2\shapeout2\gui\matrix\dm_element.py", line 90, in update_content
    curinst.update_content()
  File "C:\Users\Christoph\AppData\Local\Shape-Out 2\shapeout2\gui\matrix\dm_element.py", line 102, in update_content
    self.setStyleSheet("background-color:{}".format(color))
RuntimeError: wrapped C/C++ object of type MatrixElement has been deleted
```

I guess its an issue with the matrix the QV expects to find. it is not an issue if the matrix is extended. It remains an issue if a (e.g.) filterset is removed and one is added.

One way to catch this would either to try and still find the correct location it last was or to just display the initial message to select a field by shift+click again which would anyway be necessary in case the QV selection was removed.

(PS. Deef started to play with the program, hunting for exceptions :)

**Comment by paulmueller** [comment]
The TypeError is fixed by 25fcaf1
